### ISSUE TITLE
SEM README

### ISSUE THREAD

**Issue by guibaux** [rEiNbU-gAi/estoque#1]
Adicione um README e Licença pelo bem dos bons

**Comment by rEiNbU-gAi** [comment]
Quando eu terminar eu vou

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Guilherme Corrêa Torquato <notifications@github.com>
Enviado: Wednesday, May 6, 2020 8:37:09 PM
Para: rEiNbU-gAi/estoque <estoque@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [rEiNbU-gAi/estoque] SEM README (#1)


Adicione um README e Licença pelo bem dos bons
